routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

//Route::get('/', function () {
//    return view('website.home');
//});

Route::get('/', 'IndexController@getHome')->name('index');
Route::get('/monitores', 'IndexController@getMonitores')->name('monitores');
Route::get('/fotos', 'IndexController@getFotos')->name('fotos');
Route::get('/contato', 'IndexController@contato')->name('contato');
Route::post('/contato', 'IndexController@postContato')->name('contato.send');
Route::get('/quizbiblico', 'QuizBiblicoController@index')->name('quizbiblico');
Route::get('/gerar-quiz', 'QuizBiblicoController@gerar_quiz')->name('quiz.gerar');
Route::post('/quiz-enviar', 'QuizBiblicoController@enviar_quiz')->name('quiz.enviar');






//Auth::routes();
Auth::routes(['register' => false]);
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/matricula', 'HomeController@form_matricula')->name('form.matricula');
Route::get('/matricula/editar', 'HomeController@editar_matricula')->name('editar.matricula');
Route::post('/enviar-matricula', 'HomeController@enviar_matricula')->name('matricula');
Route::post('/editar-matricula', 'HomeController@update_matricula')->name('update.matricula');


Route::group([
    'prefix' => 'aluno', 'as' => 'aluno.',
   
    'namespace' => 'Aluno',
    ], function () {
    
//    Route::get('/redirect', 'SocialAuthFacebookController@redirect');
//Route::get('/callback', 'SocialAuthFacebookController@callback');
//
Route::get('login/facebook', 'Auth\LoginController@redirectToProvider')->name('facebook');
Route::get('login/facebook/callback', 'Auth\LoginController@handleProviderCallback');
//Route::get('login/facebook/fblogin', 'Auth\LoginController@fblogin');
Route::get('login/google', 'Auth\LoginController@redirectToProviderGoogle')->name('google');
Route::get('login/google/callback', 'Auth\LoginController@handleProviderCallbackGoogle');

    Route::get('/', 'Auth\LoginController@showLoginForm')->name('index');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/dados', 'HomeController@dados_aluno')->name('dados');
    Route::post('/matricula', 'HomeController@enviar_matricula')->name('matricula');
    Route::post('/matricula/editar', 'HomeController@editar_matricula')->name('editar');
// Authentication Routes…
    $this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
    $this->post('login', 'Auth\LoginController@login')->name('login');
    $this->post('logout', 'Auth\LoginController@logout')->name('logout');
    
// Registration Routes...
    $this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
    $this->post('register', 'Auth\RegisterController@register');    

// Password Reset Routes…
    $this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    $this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    $this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    $this->post('password/reset', 'Auth\ResetPasswordController@reset');
});

resources/views/partials/footer.blade.php
<!-- Footer -->
  <footer class="bg-light py-5">
    <div class="container">
      <div class="small text-center text-muted">Copyright &copy; 2020 - EETAD    
          @if($config->nmescola != null && $config->nmescola != "")
            {{$config->nmescola}}    
            @endif
          &nbsp;&nbsp;-&nbsp;&nbsp;
          <a href="{{ url('/admin') }}" target="_blank"><i class="fa fa-lock"></i> Admin</a>
          
      </div> 
      
      
    </div>
  </footer>

resources/views/partials/head.blade.php
<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Site da EETAD Núcleo 0325 - Coronel Fabriciano e Ipatinga">
  <meta name="author" content="">
  <meta property="og:site_name" content="EETAD 0325"/>
  <meta property="og:title" content="@yield('titulo')" />
  <meta property="og:image" content="{{ asset('img/logo.png') }}" />
  <meta property="og:image:width" content="244">
  <meta property="og:image:height" content="200">
  
  <meta property="og:type" content="website" />

  <meta property="og:url" content="http://www.eetad0325.com.br/" />
  <meta property="og:description" content="Site da EETAD Núcleo 0325 - Coronel Fabriciano e Ipatinga">
  
        <title>@yield('titulo')</title>

       
        <link rel="shortcut icon" href="img/eetad.ico">
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="img/eetad_128x128.ico">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="img/eetad_128x128.ico">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="eetad_64x64.ico">
        <link rel="apple-touch-icon-precomposed" href="eetad_64x64.ico">
@yield('metafacebook')


@include('partials.styles')

resources/views/partials/header.blade.php
 <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="#page-top">
       @if(isset($config) && $config->count() > 0)
       <a href="{{route('index')}}" class="links" >
         @if($config->logo != null && $config->logo != "")
         
          <img src="{{asset($config->logo)}}" alt="Logo EETAD" id="logo"/>
         @endif
         @if($config->nmescola != null && $config->nmescola != "")
         
         <span class="titulo"  >{{$config->nmescola}}</span>
         
         @endif
         </a>
      @endif
      </a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>&nbsp;Menu
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto my-2 my-lg-0">
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{{route('index')}}#about">Sobre</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{{route('index')}}#services">Diretoria/Monitores</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{{route('index')}}#portfolio">Fotos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{{route('quizbiblico')}}">Quiz Bíblico</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{{route('index')}}#contact">Contato</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{route('aluno.index')}}">Aluno</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

resources/views/partials/messages.blade.php
@if (Session::has('success'))
	<div class="alert alert-success" role="alert">
		<strong></strong> {{ Session::get('success') }}
	</div>
@elseif (Session::has('warning'))
	<div class="alert alert-warning" role="alert">
		<strong></strong> {{ Session::get('warning') }}
	</div>
@elseif (Session::has('error'))
	<div class="alert alert-danger" role="alert">
		<strong>Erro:</strong> {{ Session::get('error') }}
	</div>
@endif

@if (count($errors) > 0)
	<div class="alert alert-danger" role="alert">
		<strong>Erros:</strong> 
		<ul>
		@foreach ($errors->all() as $error)
			<li>{{ $error }}</li>
		@endforeach
		</ul>
	</div
@endif

resources/views/partials/scripts.blade.php
 <script src="js/app.js"></script>
  <!-- Bootstrap core JavaScript -->
  <!--<script src="vendor/jquery/jquery.min.js"></script>-->
  
  <script src="js/jquery-1.11.1.min.js"></script>
  <script src="js/jquery.mask.min.js"></script>
  <script src="js/jquery.validate.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Plugin JavaScript -->
  <script src="vendor/jquery-easing/jquery.easing.min.js"></script>
  <script src="vendor/magnific-popup/jquery.magnific-popup.min.js"></script>

  <!-- Custom scripts for this template -->
  <script src="js/creative.min.js"></script>
  
  <script src="js/custom.js"></script>
<!-- Go to www.addthis.com/dashboard to customize your tools -->
<!-- Go to www.addthis.com/dashboard to customize your tools -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5e63d49c11528465"></script>

        @yield('scripts')

resources/views/partials/styles.blade.php
<!-- Font Awesome Icons -->
  <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic' rel='stylesheet' type='text/css'>

  <!-- Plugin CSS -->
  <link href="vendor/magnific-popup/magnific-popup.css" rel="stylesheet">

  <!-- Theme CSS - Includes Bootstrap -->
  <link href="css/creative.css" rel="stylesheet">
  <link href="css/main.css" rel="stylesheet">       



@yield('styles')